# Uniritter

<b>Disciplina</b>: Machine Learning I

<b>Prof. Nielsen Rechia</b>

Introdução de Numpy para ciência de dados

In [38]:
#encoding utf-8
import numpy as np

In [39]:
a = np.array([10, 20, 30]) 
print type(a)           
print a.shape         
print a[0], a[1], a[2]
a[0] = 50
print a[0]

b = np.array([[10,20,30],[40,50,60]]) 
print b.shape                    
print b[0, 0], b[0, 1], b[1, 0]

<type 'numpy.ndarray'>
(3,)
10 20 30
50
(2, 3)
10 20 40


In [40]:
zeros = np.zeros((5,5))  # zeros
ones = np.ones((1,2)) # uns
equals = np.full((2,2), 7)  # replicada
identity = np.eye(2)  # identidade 
randons = np.random.random((2,2))  # randômico

print zeros
print ones
print equals
print identity
print randons

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.  1.]]
[[7 7]
 [7 7]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.14833466  0.8600226 ]
 [ 0.00632578  0.3987702 ]]


In [41]:
a = np.array([[10,20,30,40], [50,60,70,80], [90,100,110,120]])
print a

b = a[:2, 1:3]
print b
print a[0, 1]   
b[0, 0] = 77
print b
print a[0, 1]

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[[20 30]
 [60 70]]
20
[[77 30]
 [60 70]]
77


In [42]:
a = np.array([[10,20,30,40], [50,60,70,80], [90,100,110,120]])
print a

row1 = a[1, :]     
row2 = a[1:2, :]
print row1, row1.shape 
print row2, row2.shape 

col1 = a[:, 1]
col2 = a[:, 1:2]
print col1, col1.shape 
print col2, col2.shape

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[50 60 70 80] (4,)
[[50 60 70 80]] (1, 4)
[ 20  60 100] (3,)
[[ 20]
 [ 60]
 [100]] (3, 1)


In [56]:
a = np.arange(3*3).reshape(3,3)
print a
print a*3
print a/3
print a+3
print a-3
print a**2

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]
[[0 0 0]
 [1 1 1]
 [2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-3 -2 -1]
 [ 0  1  2]
 [ 3  4  5]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [43]:
x = np.array([[10,20],[30,40]], dtype=np.float64)
print x
y = np.array([[50,60],[70,80]], dtype=np.float64)
print y

print x + y
print np.add(x, y)

print x - y
print np.subtract(x, y)

[[ 10.  20.]
 [ 30.  40.]]
[[ 50.  60.]
 [ 70.  80.]]
[[  60.   80.]
 [ 100.  120.]]
[[  60.   80.]
 [ 100.  120.]]
[[-40. -40.]
 [-40. -40.]]
[[-40. -40.]
 [-40. -40.]]


In [44]:
x = np.array([[10,20],[30,40]], dtype=np.float64)
print x
y = np.array([[50,60],[70,80]], dtype=np.float64)
print y

print x * y
print np.multiply(x, y)

print x / y
print np.divide(x, y)
print np.sqrt(x)

[[ 10.  20.]
 [ 30.  40.]]
[[ 50.  60.]
 [ 70.  80.]]
[[  500.  1200.]
 [ 2100.  3200.]]
[[  500.  1200.]
 [ 2100.  3200.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 3.16227766  4.47213595]
 [ 5.47722558  6.32455532]]


In [45]:
x = np.array([[10,20],[30,40]])
print x
y = np.array([[50,60],[70,80]])
print y
v = np.array([90,100])
print v
w = np.array([110, 120])
print w

[[10 20]
 [30 40]]
[[50 60]
 [70 80]]
[ 90 100]
[110 120]


In [46]:
print v.dot(w)
print np.dot(v,w)
print x.dot(v)
print np.dot(x,v)
print x.dot(y)
print np.dot(x,y)

21900
21900
[2900 6700]
[2900 6700]
[[1900 2200]
 [4300 5000]]
[[1900 2200]
 [4300 5000]]


In [47]:
x = np.array([[10,20], [30,40]])
print x

print np.sum(x) 
print np.sum(x, axis=0) 
print np.sum(x, axis=1)

[[10 20]
 [30 40]]
100
[40 60]
[30 70]


In [48]:
x = np.array([[10,20], [30,40]])
print x   
print x.T 

v = np.array([40,50,60])
print v   
print v.T

w = np.matrix(v)
print w
print w.T

[[10 20]
 [30 40]]
[[10 30]
 [20 40]]
[40 50 60]
[40 50 60]
[[40 50 60]]
[[40]
 [50]
 [60]]


In [49]:
x = np.array([-10, 10, 0, 1, 1, 7, 11, 5, 4, 3])

max = np.max(x)
print max

11


In [51]:
a = np.array([[10, 20, 30]]) 
b = np.array([[10,20,30],[40,50,60]]) 
c = np.concatenate((a, b), axis=0)

print c

d = np.array([[1, 2, 3]])
print d
e = np.concatenate((c, d.T), axis=1)
print e

[[10 20 30]
 [10 20 30]
 [40 50 60]]
[[1 2 3]]
[[10 20 30  1]
 [10 20 30  2]
 [40 50 60  3]]


In [52]:
a = np.ones((2,1))
b = np.zeros((2,2))
print a
print b
print a.shape
print a.reshape(1,2)
print np.hstack((a,[[7],[8]]))
print np.vstack((b,[[1,2],[3,4]]))

[[ 1.]
 [ 1.]]
[[ 0.  0.]
 [ 0.  0.]]
(2, 1)
[[ 1.  1.]]
[[ 1.  7.]
 [ 1.  8.]]
[[ 0.  0.]
 [ 0.  0.]
 [ 1.  2.]
 [ 3.  4.]]
