In [3]:
# encoding=utf-8
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import euclidean_distances

In [7]:
a = np.arange(10).reshape((5, 2))
b = [[0],[1],[1],[0],[0]]
b = np.array([1,0,1,0,0])
print a
print b

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[1 0 1 0 0]


In [26]:
x_train, x_test, y_train, y_test = train_test_split(
    a, b, test_size=0.2)

print x_train
print y_train
print x_test
print y_test

[[0 1]
 [2 3]
 [8 9]
 [6 7]]
[1 0 0 0]
[[4 5]]
[1]


In [23]:
data = load_iris()
data = pd.DataFrame(np.hstack((data['data'], data['target'].reshape(data['target'].shape[0], 1))), 
                    columns=data['feature_names'] + ['class']
)

X = data[data.columns[:-1]]
Y = data[data.columns[-1]]
# print Y

t1 = np.array([6.1,2.1,4.7,1.3])

k = 3
dist_x = []

for idx, linha in X.iterrows():
    dist_x.append((idx, euclidean_distances(linha.values.reshape(1,-1), t1.reshape(1,-1))))
    
dist_sorted = sorted(dist_x, key=lambda d: d[1])[:k]

xx = [Y.iloc[idx] for idx, dist in dist_sorted]

print xx

print sorted([(classe, xx.count(classe)) 
        for classe in Y.unique()], key=lambda a: a[1], reverse=True)[0][0]

t2 = np.array([6.6,3.1,5.7,2.1])

k = 3
dist_x = []

for idx, linha in X.iterrows():
    dist_x.append((idx, euclidean_distances(linha.values.reshape(1,-1), t2.reshape(1,-1))))
    
dist_sorted = sorted(dist_x, key=lambda d: d[1])[:k]

xx = [Y.iloc[idx] for idx, dist in dist_sorted]

print xx

print sorted([(classe, xx.count(classe)) 
        for classe in Y.unique()], key=lambda a: a[1], reverse=True)[0][0]




[1.0, 2.0, 1.0]
1.0
[2.0, 2.0, 2.0]
2.0


In [34]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import euclidean_distances

def getNeighbors(trainset, test, k):
    dist_test = []
    for id_train, train in trainset.iterrows():
        t = np.array(train[0:4])
        dist_test.append((id_train, euclidean_distances(t.reshape(1, -1), test[0:4].values.reshape(1, -1))))
    dist_sorted = sorted(dist_test, key=lambda d: d[1])[:k]
    xx = [trainset.ix[id_dist]['c'] for id_dist, dist in dist_sorted]
    return sorted([(classe, xx.count(classe)) 
                   for classe in trainset['c'].unique()], key=lambda a: a[1], reverse=True)[0][0]

def getAccuracy(testset, predictions):
    correct = 0
    for id_test, test in testset.iterrows():
        if test[-1] == predictions.ix[id_test][0]:
            correct += 1
    return (correct / float(len(testset))) * 100.0

def main():
    iris = pd.read_csv('iris.data', nrows=None, header=None, index_col=None)
    iris.reset_index()
    iris.columns = ['sl', 'sw', 'pl', 'pw', 'c']
    trainset, testset, = train_test_split(iris, test_size=0.2)
    predictions = []
    k = 9
    for id_test, test in testset.iterrows():
        predicted = getNeighbors(trainset, test, k)
        predictions.append(predicted)
        # print('> predicted=' + str(predicted) + ', actual=' + str(test[-1]))
    accuracy = getAccuracy(testset, pd.DataFrame(predictions, index=testset.index.values))
    print accuracy
main()

C:\ProgramData\Anaconda2\lib\site-packages\ipykernel_launcher.py:12: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if sys.path[0] == '':


100.0


C:\ProgramData\Anaconda2\lib\site-packages\ipykernel_launcher.py:19: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated


In [38]:
#EXEMPLO IMPORTANDO
from sklearn.neighbors import KNeighborsClassifier

iris = pd.read_csv('iris.data', nrows=None, header=None, index_col=None)

trainset, testset, = train_test_split(iris, test_size=0.2)

knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(trainset.iloc[:, 0:-1], trainset.iloc[:, -1])
predicted_knn = knn.predict(testset.iloc[:, 0:-1])
print predicted_knn
print testset.iloc[:, -1]

['Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica']
75     Iris-versicolor
3          Iris-setosa
78     Iris-versicolor
106     Iris-virginica
86     Iris-versicolor
140     Iris-virginica
5          Iris-setosa
97     Iris-versicolor
108     Iris-virginica
42         Iris-setosa
82     Iris-versicolor
87     Iris-versicolor
133     Iris-virginica
105     Iris-virginica
60     Iris-versicolor
35         Iris-setosa
51     Iris-versicolor
28         Iris-setosa
61     Iris-versicolor
131     Iris-virginica
32         Iris-setosa
14         Iris

In [9]:
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.neighbors import KNeighborsClassifier

def getNeighbors(trainset, test, k):
    dist_test = []
    for id_train, train in trainset.iterrows():
        t = np.array(train[:-1])
        dist_test.append((id_train, euclidean_distances(t.reshape(1, -1), test[:-1].reshape(1, -1))))
    dist_sorted = sorted(dist_test, key=lambda d: d[1])[:k]
    xx = [trainset.ix[id_dist]['classe'] for id_dist, dist in dist_sorted]
    return sorted([(classe, xx.count(classe)) for classe in trainset['classe'].unique()], key=lambda a: a[1], reverse=True)[0][0]

def getAccuracy(testset, predictions):
    correct = 0
    for id_test, test in testset.iterrows():
        if test[-1] == predictions.ix[id_test][0]:
            correct += 1
    return (correct / float(len(testset))) * 100.0


def main():
    # prepare data
    zoo = pd.read_csv('zoo.csv', nrows=None, header=0, index_col=0)
    trainset, testset, = train_test_split(zoo, test_size=0.2)

    predictions = []
    k = 2

    for id_test, test in testset.iterrows():
        predicted = getNeighbors(trainset, test, k)
        predictions.append(predicted)
        # print('> predicted=' + str(predicted) + ', actual=' + str(test[-1]))
    accuracy = getAccuracy(testset, pd.DataFrame(predictions, index=testset.index.values))
    print accuracy

    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(trainset.iloc[:, 0:-1], trainset.iloc[:, -1])
    predicted_knn = knn.predict(testset.iloc[:, 0:-1])
    accuracy = getAccuracy(testset, pd.DataFrame(predicted_knn, index=testset.index.values))
    print accuracy

main()

76.1904761905
76.1904761905
