In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [4]:
m = np.array([
        [10,20],
        [30,40],
        [50,60]
    ])
print m

[[10 20]
 [30 40]
 [50 60]]


In [5]:
print m.shape

(3, 2)


In [6]:
m1 = np.array([
        [10, 20, 30, 40],
        [35, 60, 70, 80],
        [90, 11, 12, 13]
    ])
print m1

[[10 20 30 40]
 [35 60 70 80]
 [90 11 12 13]]


In [7]:
print m1.shape

(3, 4)


In [9]:
m2 = np.array([
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]
    ])
print m2

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [10]:
print m2.shape

(3, 3)


In [15]:
ve = np.array([10, 20])

ma = np.array([
        [1,2]
    ])

print ve
print ve.shape, '= unidimensional'

[10 20]
(2,) = unidimensional


In [14]:
print ma
print ma.shape, '= multimensional'

[[1 2]]
(1, 2) = multimensional


In [16]:
ve1 = np.array([10, 20, 30, 40])
print ve1
print ve1.shape

[10 20 30 40]
(4,)


In [17]:
ma1 = np.array([[10, 20], [30, 40], [50, 60]])
print ma1
print ma1.shape

[[10 20]
 [30 40]
 [50 60]]
(3, 2)


In [18]:
ma2 = np.array([[10, 0], [20, 30]])
print ma2
print ma2.shape

[[10  0]
 [20 30]]
(2, 2)


In [21]:
result = np.dot(ma1, ma2)
print result
print result.shape

[[ 500  600]
 [1100 1200]
 [1700 1800]]
(3, 2)


In [26]:
print ma1.T
print ma1.T.shape

[[10 30 50]
 [20 40 60]]
(2, 3)


In [27]:
print np.transpose(ma1)

[[10 30 50]
 [20 40 60]]


In [28]:
a = np.array([[10, 0], [20, 40], [30, 50]])
b = np.array([[10, 20, 30], [40, 50, 60]])
c = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print np.dot(a, b)

[[ 100  200  300]
 [1800 2400 3000]
 [2300 3100 3900]]


In [29]:
print np.dot(a.T, c)

[[3000 3600 4200]
 [5100 6000 6900]]


In [31]:
print np.dot(b, c)

[[3000 3600 4200]
 [6600 8100 9600]]


In [40]:
print 1.5 + 0 * 0
print 0 + 0.5 * 0
print 1 + 0.5 * 0

1.5
0.0
1.0


In [41]:
print 1.5 + 0 * 1
print 0 + 0.5 * 1
print 1 + 0.5 * 1

1.5
0.5
1.5


In [43]:
print 1.5 + 0 * 2
print 0 + 0.5 * 2
print 1 + 0.5 * 2

1.5
1.0
2.0


In [45]:
print 1.5 + 0 * 3
print 0 + 0.5 * 3
print 1 + 0.5 * 3

1.5
1.5
2.5


In [60]:
print 0.5 + 1 * 0
print 0.5 + 1 * 1
print 0.5 + 1 * 2
print 0.5 + 1 * 3

0.5
1.5
2.5
3.5


In [62]:
print 0.0 + 0 * 0
print 0.0 + 0.5 * 1
print 0.5 + 1 * 2
print 0.5 + 1 * 3

0.0
0.5
2.5
3.5
